pipeline {
    agent any

    parameters {
        string(
            name: 'FRONTEND_DOCKER_TAG',
            defaultValue: '',
            description: 'Frontend Docker tag of the image built by the CI job'
        )

        string(
            name: 'BACKEND_DOCKER_TAG',
            defaultValue: '',
            description: 'Backend Docker tag of the image built by the CI job'
        )
    }

    stages {

        stage("Workspace Cleanup") {
            steps {
                cleanWs()
            }
        }

        stage("Git Code Checkout") {
            steps {
                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[
                        credentialsId: 'git-token',
                        url: 'https://github.com/KevinJCloud/Wanderlust_3TIER.git'
                    ]]
                )
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
            }
        }

        stage("Update: Kubernetes Manifests") {
            steps {
                script {

                    dir('kubernetes') {

                        sh """
                            sed -i 's|kevinjcloud/wanderlust:.*|kevinjcloud/wanderlust:${params.BACKEND_DOCKER_TAG}|g' backend.yaml
                        """

                        sh """
                            sed -i 's|kevinjcloud/wanderlust:.*|kevinjcloud/wanderlust:${params.FRONTEND_DOCKER_TAG}|g' frontend.yaml
                        """
                    }
                }
            }
        }

        stage("Git: Code Update and Push to GitHub") {
            steps {
                script {

                    withCredentials([
                        gitUsernamePassword(
                            credentialsId: 'git-token',
                            gitToolName: 'Default'
                        )
                    ]) {

                        sh '''
                            echo "Checking repository status:"
                            git status

                            echo "Adding changes to git:"
                            git add kubernetes/

                            echo "Committing changes:"
                            git commit -m "Update Kubernetes image tags"

                            echo "Pushing changes to GitHub:"
                            git push origin main
                        '''
                    }
                }
            }
        }
    }

    post {

        success {
            script {

                emailext(
                    attachLog: true,
                    from: 'jobinjkkumar@gmail.com',
                    subject: "Wanderlust Application has been updated and deployed - '${currentBuild.currentResult}'",
                    body: """
                        <html>
                        <body>

                            <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">
                                    Project: ${env.JOB_NAME}
                                </p>
                            </div>

                            <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">
                                    Build Number: ${env.BUILD_NUMBER}
                                </p>
                            </div>

                            <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">
                                    URL: ${env.BUILD_URL}
                                </p>
                            </div>

                        </body>
                        </html>
                    """,
                    to: 'jobinjkkumar@gmail.com',
                    mimeType: 'text/html'
                )
            }
        }

        failure {
            script {

                emailext(
                    attachLog: true,
                    from: 'jobinjkkumar@gmail.com',
                    subject: "Wanderlust Application build failed - '${currentBuild.currentResult}'",
                    body: """
                        <html>
                        <body>

                            <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">
                                    Project: ${env.JOB_NAME}
                                </p>
                            </div>

                            <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">
                                    Build Number: ${env.BUILD_NUMBER}
                                </p>
                            </div>

                            <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
                                <p style="color: black; font-weight: bold;">
                                    URL: ${env.BUILD_URL}
                                </p>
                            </div>

                        </body>
                        </html>
                    """,
                    to: 'jobinjkkumar@gmail.com',
                    mimeType: 'text/html'
                )
            }
        }
    }
}
